---
- block:

  - name: 'krbrelayx : install dependencies via pip'
    pip:
      name: ldap3
      executable: pip2
      state: present

  - name: 'krbrelayx : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      dest: /opt/krbrelayx
      force: yes
      repo: https://github.com/dirkjanm/krbrelayx.git

  - name: 'krbrelayx : set file permissions'
    file:
      path: '{{ item }}'
      mode: 0755
    with_items:
      - /opt/krbrelayx/addspn.py
      - /opt/krbrelayx/dnstool.py
      - /opt/krbrelayx/krbrelayx.py
      - /opt/krbrelayx/printerbug.py 

  - name: 'krbrelayx : create symlinks'
    file:
      src: '{{ item }}'
      dest: '/usr/local/bin/{{ item.split("/")[-1] }}'
      state: link
    with_items:
      - /opt/krbrelayx/addspn.py
      - /opt/krbrelayx/dnstool.py
      - /opt/krbrelayx/krbrelayx.py
      - /opt/krbrelayx/printerbug.py

  tags:
    - exploitation
    - krbrelayx
