---
- block:

  - name: 'pypykatz : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      dest: /opt/pypykatz
      force: yes
      repo: https://github.com/skelsec/pypykatz.git

  - name: 'pypykatz : remove existing venv'
    file:
      path: /opt/pypykatz/.venv
      state: absent

  - name: 'pypykatz : create venv directory'
    file:
      path: /opt/pypykatz/.venv
      state: directory

  - name: 'pypykatz : initialise venv'
    shell: 'bash -lc "virtualenv -p python3 /opt/pypykatz/.venv"'

  - name: 'pypykatz : install requirements'
    pip:
      name: ['minidump','minikerberos','aiowinreg','msldap','winsspi']
      state: present
      virtualenv: /opt/pypykatz/.venv

  - name: 'pypykatz : install via pip'
    pip:
      name: git+https://github.com/skelsec/pypykatz
      state: present
      virtualenv: /opt/pypykatz/.venv

  - name: 'pypykatz : install launcher'
    template:
      dest: /usr/local/bin/pypykatz
      mode: 0755
      src: ../templates/pypykatz.sh

  tags:
    - exploitation
    - pypykatz
