---
- block:

  - name: 'ruby : install ruby'
    apt:
      name: ruby
      state: present

  - name: 'ruby : install bundler'
    apt:
      name: ruby-bundler
      state: present

  - name: 'ruby : install ruby-dev'
    apt:
      name: ruby-dev
      state: present

  tags:
    - common
    - ruby
    - evil-winrm
    - metasploit
    - snmp-check
    - whatweb
    - wpscan
    - wpxf
